version: '3.8'
services:

  postgres:
    build:
      dockerfile: postgres.dockerfile

  bdjuno:
    build:
      dockerfile: bdjuno.dockerfile
    depends_on:
      - postgres
    volumes:
      - ./bdjuno-config.yaml:/etc/bdjuno/config.yaml

  hasura-postgres:
    image: postgres:16-alpine
    environment: 
      POSTGRES_PASSWORD: root
      POSTGRES_DB: hasura
  
  hasura:
    build:
      dockerfile: hasura.dockerfile
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:root@postgres:5432/bdjuno
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://postgres:root@hasura-postgres:5432/hasura
        #HASURA_GRAPHQL_UNAUTHORIZED_ROLE: "anonymous"
      ACTION_BASE_URL: http://bdjuno:3000
      HASURA_GRAPHQL_ENABLE_CONSOLE: 'true'
    depends_on:
      - hasura-postgres
      - postgres
    ports:
      - 8080:8080

  ui:
    build:
      dockerfile: big-dipper.dockerfile
    ports:
      - 3000:3000
    environment:
      GRAPHQL_URL: https://gql.explorer.testnet1.source.network/v1/graphql
      GRAPHQL_WS: ws://gql.explorer.testnet1.source.network/v1/graphql
    depends_on:
      - hasura

  pgadmin:
    image: elestio/pgadmin:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: root@root.com
      PGADMIN_DEFAULT_PASSWORD: root
      PGADMIN_LISTEN_PORT: 8080
    ports:
      - 8888:8080
    volumes:
      - ./servers.json:/pgadmin4/servers.json

  caddy:
    image: caddy:2.7
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    ports:
      - 80:80
      - 443:443
