{
 "title": "CometBFT Main",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Consensus", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Chain height",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 1 },
   "targets": [
    { "expr": "cometbft_consensus_height", "legendFormat": "{{job}}" },
    {
     "expr": "sum(cometbft_consensus_height)/ count(count by (job) (cometbft_consensus_height))",
     "legendFormat": "mean"
    }
   ]
  },
  {
   "title": "Chain size (#txs)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 18, "x": 0, "y": 8 },
   "targets": [
    { "expr": "cometbft_consensus_total_txs", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Block size (kb)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 18, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "cometbft_consensus_block_size_bytes/1024",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Round number",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 18, "x": 0, "y": 19 },
   "targets": [
    { "expr": "cometbft_consensus_rounds", "legendFormat": "{{job}}" }
   ]
  },
  { "title": "P2P", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Sent kb per message type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "(sum(rate(cometbft_p2p_message_send_bytes_total[1m])) by (message_type))/1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Received kb per message type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "(sum(rate(cometbft_p2p_message_receive_bytes_total[1m])) by (message_type))/1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of peers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 41 },
   "targets": [
    { "expr": "cometbft_p2p_peers", "legendFormat": "{{job}}" }
   ]
  },
  { "title": "Mempool", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "Mempool size (#txs)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 50 },
   "targets": [
    { "expr": "cometbft_mempool_size", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Size of txs (kb) added to the mempool",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 58 },
   "targets": [
    {
     "expr": "rate(cometbft_mempool_tx_size_bytes_sum[$__rate_interval])/2014",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Received kb (only mempool messages)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 66 },
   "targets": [
    {
     "expr": "rate(cometbft_p2p_message_receive_bytes_total{message_type=~\"mempool_Txs|mempool_Message|mempool_WantTx|mempool_SeenTx\"}[$__rate_interval])/1024",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Sent kb (only mempool messages)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 74 },
   "targets": [
    {
     "expr": "rate(cometbft_p2p_message_send_bytes_total{message_type=~\"mempool_Txs|mempool_Message|mempool_SeenTx|mempool_WantTx\"}[$__rate_interval])/1024",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Recheck rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 82 },
   "targets": [
    {
     "expr": "sum(rate(cometbft_mempool_recheck_times[1m])) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Already received txs (rate)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 90 },
   "targets": [
    {
     "expr": "rate(cometbft_mempool_already_received_txs[$__rate_interval])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Txs rejected by the app (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 98 },
   "targets": [
    {
     "expr": "cometbft_mempool_failed_txs / (cometbft_mempool_failed_txs + cometbft_consensus_total_txs) * 100",
     "legendFormat": "{{job}}"
    }
   ]
  },
  { "title": "BlockSync", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 106 } },
  {
   "title": "Block syncing",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 107 },
   "targets": [
    { "expr": "cometbft_blocksync_syncing", "legendFormat": "{{job}}" }
   ]
  }
 ]
}