apiVersion: v1
kind: ConfigMap
metadata:
  name: bdjuno-conf
data:
  genesis_url: http://abc.com

  config.yaml: |
    chain:
      bech32_prefix: source
      modules: 
        - modules
        - messages
        - auth
        - bank
        - consensus
        - gov
        - staking
        - actions
    node:
      type: remote
      config:
        rpc:
          client_name: juno
          address: http://54.205.25.30:26657
          max_connections: 20
        grpc:
          address: 54.205.25.30:9090
          insecure: true

    parsing:
      workers: 1
      start_height: 625126
      average_block_time: 5s
      listen_new_blocks: true
      parse_old_blocks: true
      parse_genesis: true

    database:
      url: postgresql://postgres:root@postgres:5432/bdjuno?sslmode=disable&search_path=public
      max_open_connections: 1
      max_idle_connections: 1
      partition_size: 100000
      partition_batch: 1000
      ssl_mode_enable: "false"
      ssl_root_cert: ""
      ssl_cert: ""
      ssl_key: ""

    logging:
        level: debug
        format: text

    actions:
      host: 0.0.0.0
      port: 3000

    telemetry:
      enabled: true
      port: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: bdjuno-srv
  labels:
    app: bdjuno
spec:
  selector:
    app: bdjuno
  ports:
    - protocol: TCP
      port: 8000
      http-prometheus-metrics
    - protocol: TCP
      port: 3000
      targetPort: http-hasura-actions
---
apiVersion: v1
kind: Deployment
metadata:
  name: bdjuno
  labels:
    app: bdjuno
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bdjuno
  template:
    metadata:
      labels:
        app: bdjuno
    spec:
      containers:
        - name: bdjuno
          image: sourcenetwork/bdjuno:latest
          ports:
            - containerPort: 3000
              name: http-hasura-actions
            - containerPort: 8000
              name: http-prometheus-metrics

# TODO figure out how to wait for pgres
# mount config map
